# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- react

pool:
  name: Default

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'

- task: Npm@1
  displayName: 'Install dependencies'
  inputs:
    command: 'install'

- task: Npm@1
  displayName: 'Run tests'
  inputs:
    command: 'custom'

- task: PublishTestResults@2
  displayName: 'Publish test results'
  inputs:
    testResultsFiles: '**/jest.xml'
    searchFolder: $(System.DefaultWorkingDirectory)
